name: GitHub Actions - Configuração de Secret de Repositorio
run-name: Running - Secret Repo Config
on: [push, workflow_dispatch]
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentario
        run: |
          echo "${{secrets.teste_secret}}"

