name: Github actions - Pull Request Template Basico
run-name: Running - ${{ github.event_name}}
on: [pull_request]

jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentário
        run: |
          echo "Comentario PULL REQUEST WORKFLOW - Basic"
