name: GitHub Actions - Workflow run Types
run-name: Running - Workflow run Types
on: 
  workflow_run:
    workflows: [GitHub Actions - Trigger 1]
    types: [completed]
    #types: [requested]
    #types: [in_progress]
    #types: [completed, requested. in_progess]
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentario
        run: |
          echo "Workflow que foi trigado"
