name: Github actions - Push - Branch Template
run-name: Running - ${{ github.event_name}}
on:
  push:
    branches-ignore:
      - main

jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentário
        run: |
          echo "Comentario PUSH WORKFlOW - branch Ignore"
